### ISSUE TITLE
Changing Background-color through JSON

### ISSUE THREAD

**Issue by marisaaquilina** [LoganCSC/inspiration-fortune-cookie#13]
Instead of specifying the mood's background-color in the JS function, access the background-color hexadecimal from the JSON.

**Comment by barrybecker4** [comment]
The background color to use could from from the json file.
I would suggest that you modify the json structure like this
{code}
{
   emotion1 : {
      color: "#33ff55"
      fortunes: [ <list of fortunes> ]
  },
  emotion2 : {
      color: "#3366ee"
      fortunes: [ <list of fortunes> ]
  },
 ...
}
{code}

**Comment by marisaaquilina** [comment]
I modified the json structure to include color

**Comment by barrybecker4** [comment]
This is working now.
